import { StyleSheet, Dimensions, Platform } from 'react-native';

const { width: SCREEN_WIDTH } = Dimensions.get('window');

// Color scheme matching Atmosphere web (dark grey theme)
export const COLORS = {
    primary: '#3d3d3d',       // Sophisticated grey
    primaryHover: '#4d4d4d',
    accent: '#4d4d4d',
    success: '#22c55e',       // Green for success states
    background: '#0a0a0a',
    card: '#0d0d0d',
    cardHover: '#121212',
    border: '#333333',
    text: '#f5f5f5',
    textMuted: '#a3a3a3',
    textPlaceholder: '#666666',
    error: '#ef4444',
};

export const styles = StyleSheet.create({
    container: {
        flex: 1,
    },
    header: {
        height: 64,
        paddingHorizontal: 12,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        borderBottomWidth: StyleSheet.hairlineWidth,
        borderBottomColor: COLORS.border,
    },
    headerButton: {
        width: 48,
        height: 48,
        alignItems: 'center',
        justifyContent: 'center',
    },
    headerTitle: {
        fontSize: 18,
        fontWeight: '700',
    },
    shareButton: {
        backgroundColor: COLORS.primary,
        paddingHorizontal: 20,
        paddingVertical: 10,
        borderRadius: 8,
        minWidth: 70,
        alignItems: 'center',
    },
    shareButtonText: {
        color: '#fff',
        fontWeight: '700',
        fontSize: 14,
    },
    content: {
        flex: 1,
    },
    contentContainer: {
        padding: 16,
        paddingBottom: 100,
    },
    videoPicker: {
        width: '100%',
        height: 400,
        backgroundColor: '#000',
        marginBottom: 16,
    },
    videoPlaceholder: {
        width: '100%',
        height: '100%',
        borderWidth: 2,
        borderStyle: 'dashed',
        borderRadius: 16,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: COLORS.card,
    },
    placeholderIconContainer: {
        width: 80,
        height: 80,
        borderRadius: 40,
        backgroundColor: COLORS.cardHover,
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 16,
    },
    videoPreviewContainer: {
        width: '100%',
        height: '100%',
        backgroundColor: '#000',
    },
    videoPreviewImage: {
        width: '100%',
        height: '100%',
        position: 'absolute',
        top: 0,
        left: 0,
        bottom: 0,
        right: 0,
    },
    playIndicator: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        alignItems: 'center',
        justifyContent: 'center',
    },
    videoOverlay: {
        position: 'absolute',
        top: 12,
        left: 12,
    },
    videoInfoBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(0,0,0,0.6)',
        paddingHorizontal: 10,
        paddingVertical: 6,
        borderRadius: 16,
        gap: 6,
    },
    videoInfoText: {
        color: '#fff',
        fontSize: 12,
        fontWeight: '600',
    },
    changeVideoOverlay: {
        position: 'absolute',
        bottom: 12,
        right: 12,
        zIndex: 10,
    },
    changeVideoBtn: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(0,0,0,0.7)',
        paddingHorizontal: 14,
        paddingVertical: 8,
        borderRadius: 20,
        gap: 6,
    },
    changeVideoText: {
        color: '#fff',
        fontWeight: '600',
        fontSize: 13,
    },
    placeholderText: {
        fontSize: 16,
        fontWeight: '600',
    },
    placeholderHint: {
        fontSize: 13,
        marginTop: 6,
    },
    uploadStatus: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        padding: 8,
        backgroundColor: COLORS.cardHover,
    },
    uploadStatusText: {
        marginLeft: 8,
        fontSize: 14,
    },
    // Cover Section Styles
    coverSection: {
        marginBottom: 24,
        backgroundColor: COLORS.card,
        borderRadius: 12,
        padding: 16,
        borderWidth: 1,
        borderColor: COLORS.border,
    },
    coverSectionTitle: {
        fontSize: 16,
        fontWeight: '600',
        marginBottom: 16,
    },
    timelineContainer: {
        marginBottom: 16,
        height: 80,
        justifyContent: 'center',
        paddingHorizontal: 0,
    },
    filmstripContainer: {
        flexDirection: 'row',
        height: 50,
        backgroundColor: '#000',
        borderRadius: 8,
        overflow: 'hidden',
        width: '100%',
        position: 'absolute',
        top: 0,
    },
    filmstripFrameContainer: {
        width: SCREEN_WIDTH / 6,
        height: 50,
        borderRightWidth: 1,
        borderRightColor: '#000',
        backgroundColor: '#222',
    },
    filmstripFrame: {
        width: '100%',
        height: '100%',
        opacity: 0.8,
        backgroundColor: '#333',
    },
    slider: {
        width: '100%',
        height: 40,
    },
    sliderOverlay: {
        width: '100%',
        height: 50,
        position: 'absolute',
        top: 0,
        zIndex: 10,
    },
    timelineLabels: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        paddingHorizontal: 4,
        marginTop: 54,
    },
    timelineTime: {
        color: COLORS.textMuted,
        fontSize: 12,
    },
    timelineHint: {
        color: COLORS.textMuted,
        fontSize: 12,
        textAlign: 'center',
        marginTop: 4,
    },
    divider: {
        height: 1,
        backgroundColor: COLORS.border,
        marginVertical: 16,
    },
    coverOptionsRow: {
        flexDirection: 'row',
        justifyContent: 'center',
    },
    galleryBtn: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 12,
        paddingHorizontal: 20,
        backgroundColor: COLORS.cardHover,
        borderRadius: 8,
        gap: 8,
        width: '100%',
    },
    galleryBtnText: {
        color: COLORS.text,
        fontSize: 14,
        fontWeight: '500',
    },
    customCoverPreview: {
        flexDirection: 'row',
        alignItems: 'center',
        width: '100%',
        backgroundColor: COLORS.cardHover,
        padding: 12,
        borderRadius: 8,
        gap: 12,
    },
    customCoverImage: {
        width: 48,
        height: 48,
        borderRadius: 6,
        backgroundColor: '#000',
    },
    customCoverInfo: {
        flex: 1,
    },
    customCoverLabel: {
        color: COLORS.text,
        fontSize: 14,
        fontWeight: '500',
        marginBottom: 4,
    },
    removeCoverLink: {
        alignSelf: 'flex-start',
    },
    removeCoverText: {
        color: COLORS.error,
        fontSize: 13,
        fontWeight: '500',
    },
    // Inputs
    inputSection: {
        marginBottom: 20,
    },
    inputLabel: {
        fontSize: 14,
        fontWeight: '600',
        marginBottom: 8,
        marginLeft: 4,
    },
    textInput: {
        backgroundColor: COLORS.card,
        borderRadius: 12,
        padding: 12,
        fontSize: 15,
        borderWidth: 1,
        minHeight: 100,
    },
    tagInput: {
        backgroundColor: COLORS.card,
        borderRadius: 12,
        padding: 12,
        fontSize: 15,
        borderWidth: 1,
    },
    // Step 1 Styles
    fullScreenContainer: {
        flex: 1,
        backgroundColor: '#000',
    },
    fullScreenVideo: {
        width: '100%',
        height: '100%',
        backgroundColor: '#000',
    },
    step1Header: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        flexDirection: 'row',
        justifyContent: 'space-between',
        padding: 16,
        paddingTop: Platform.OS === 'android' ? 16 : 48,
        zIndex: 10,
    },
    iconBtn: {
        width: 44,
        height: 44,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'rgba(0,0,0,0.3)',
        borderRadius: 22,
    },
    nextBtn: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#fff',
        paddingHorizontal: 20,
        paddingVertical: 10,
        borderRadius: 24,
        gap: 4,
    },
    nextBtnText: {
        color: '#000',
        fontWeight: '700',
        fontSize: 14,
    },
    step1Footer: {
        position: 'absolute',
        bottom: 100,
        left: 0,
        right: 0,
        alignItems: 'center',
    },
    trimBtn: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(50,50,50,0.8)',
        paddingHorizontal: 24,
        paddingVertical: 14,
        borderRadius: 28,
        gap: 8,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.2)',
    },
    trimBtnText: {
        color: '#fff',
        fontWeight: '600',
        fontSize: 16,
    },
    // Step 2 Styles
    detailsVideoPreview: {
        width: '100%',
        height: 400,
        backgroundColor: '#111',
        marginBottom: 20,
        position: 'relative',
    },
    previewVideo: {
        width: '100%',
        height: 320,
    },
    coverSelectorContainer: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        height: 80,
        backgroundColor: 'rgba(0,0,0,0.9)',
        paddingHorizontal: 16,
        justifyContent: 'center',
    },
    helperText: {
        color: '#ccc',
        fontSize: 12,
        marginBottom: 8,
        textAlign: 'center',
        marginTop: 4,
    },
    detailsForm: {
        paddingHorizontal: 16,
    },
    captionInput: {
        fontSize: 16,
        minHeight: 80,
        textAlignVertical: 'top',
    },
    coverOptionsModal: {
        width: '100%',
        maxWidth: 340,
        backgroundColor: COLORS.card,
        borderRadius: 16,
        padding: 24,
        alignItems: 'center',
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
    },
    coverOptionsTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: COLORS.text,
        marginBottom: 24,
    },
    coverOption: {
        flexDirection: 'row',
        alignItems: 'center',
        width: '100%',
        padding: 16,
        backgroundColor: COLORS.background,
        borderRadius: 12,
        marginBottom: 12,
        gap: 16,
    },
    coverOptionTextContainer: {
        flex: 1,
    },
    coverOptionText: {
        fontSize: 16,
        fontWeight: '600',
        color: COLORS.text,
        marginBottom: 4,
    },
    coverOptionHint: {
        fontSize: 13,
        color: COLORS.textMuted,
    },
    coverCancelBtn: {
        marginTop: 12,
        padding: 12,
    },
    coverCancelText: {
        color: COLORS.textMuted,
        fontSize: 15,
        fontWeight: '600',
    },
});
