import { Dimensions, StyleSheet } from 'react-native';

export const { width, height } = Dimensions.get('window');

export const styles = StyleSheet.create({
    container: {
        flex: 1,
    },
    centerContent: {
        justifyContent: 'center',
        alignItems: 'center',
    },
    loadingText: {
        marginTop: 16,
        fontSize: 16,
    },
    mainVideoArea: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    largeLocalVideoContainer: {
        width: width * 0.9,
        height: height * 0.6,
        borderRadius: 20,
        overflow: 'hidden',
        backgroundColor: '#2a2a2a',
        elevation: 8,
    },
    largeLocalUserInfo: {
        position: 'absolute',
        bottom: 20,
        left: 20,
        backgroundColor: 'rgba(0,0,0,0.6)',
        paddingHorizontal: 16,
        paddingVertical: 8,
        borderRadius: 12,
    },
    largeLocalUserText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '700',
    },
    noParticipants: {
        marginTop: 40,
        alignItems: 'center',
        padding: 20,
    },
    noParticipantsText: {
        color: '#999',
        fontSize: 16,
        marginTop: 12,
        textAlign: 'center',
    },
    noParticipantsSubtext: {
        color: '#999',
        fontSize: 14,
        marginTop: 8,
        textAlign: 'center',
    },
    remoteContainer: {
        flex: 1,
        backgroundColor: '#1a1a1a',
    },
    participantGrid: {
        padding: 8,
        alignItems: 'center',
    },
    remoteVideoContainer: {
        margin: 4,
        borderRadius: 12,
        overflow: 'hidden',
        backgroundColor: '#2a2a2a',
        elevation: 2,
    },
    remoteVideo: {
        width: '100%',
        height: '100%',
    },
    remoteUserInfo: {
        position: 'absolute',
        bottom: 12,
        left: 12,
        backgroundColor: 'rgba(0,0,0,0.6)',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 6,
    },
    remoteUserText: {
        color: '#fff',
        fontSize: 13,
        fontWeight: '600',
    },
    smallLocalVideoWrapper: {
        position: 'absolute',
        top: 60,
        right: 16,
        width: 120,
        height: 160,
        borderRadius: 12,
        overflow: 'hidden',
        borderWidth: 2,
        borderColor: '#fff',
        backgroundColor: '#2a2a2a',
        elevation: 10,
        zIndex: 10,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
    },
    localVideo: {
        width: '100%',
        height: '100%',
    },
    localUserInfo: {
        position: 'absolute',
        bottom: 8,
        left: 8,
        backgroundColor: 'rgba(0,0,0,0.6)',
        paddingHorizontal: 6,
        paddingVertical: 2,
        borderRadius: 4,
    },
    localUserText: {
        color: '#fff',
        fontSize: 10,
        fontWeight: '600',
    },
    videoPlaceholder: {
        width: '100%',
        height: '100%',
        justifyContent: 'center',
        alignItems: 'center',
    },
    placeholderText: {
        color: '#fff',
        fontSize: 12,
        marginTop: 8,
    },
    controlsContainer: {
        position: 'absolute',
        bottom: 80,
        left: 0,
        right: 0,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 20,
    },
    controlButton: {
        width: 56,
        height: 56,
        borderRadius: 28,
        backgroundColor: 'rgba(255,255,255,0.2)',
        justifyContent: 'center',
        alignItems: 'center',
        marginHorizontal: 8,
    },
    controlButtonActive: {
        backgroundColor: '#e74c3c',
    },
    leaveButton: {
        backgroundColor: '#e74c3c',
    },
    infoContainer: {
        position: 'absolute',
        top: 12,
        left: 16,
        backgroundColor: 'rgba(0,0,0,0.6)',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 8,
        zIndex: 20,
    },
    infoText: {
        color: '#fff',
        fontSize: 14,
        fontWeight: '600',
    },
    blackBackground: {
        backgroundColor: '#000',
    },
});
