import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    card: {
        borderWidth: 0,
        marginVertical: 0,
        overflow: 'hidden',
        marginHorizontal: 0,
        backgroundColor: '#0a0a0a',
    },
    headerTop: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 12,
        paddingVertical: 10,
    },
    headerLeftRow: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
        gap: 12,
    },
    headerLeft: { marginLeft: 0 },
    avatar: {
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: '#1a1a1a',
        borderWidth: 2,
        borderColor: '#333',
    },
    followBtn: {
        paddingVertical: 6,
        paddingHorizontal: 12,
        borderRadius: 6,
        backgroundColor: '#262626',
    },
    followBtnActive: { backgroundColor: '#262626' },
    followBtnText: { color: '#fff', fontWeight: '500', fontSize: 12 },
    followBtnTextActive: { color: '#fff' },
    companyName: { fontWeight: '600', fontSize: 14 },
    verifiedSmall: { color: '#888', fontSize: 10, marginTop: 2 },
    imageWrap: { paddingHorizontal: 0, paddingTop: 0, position: 'relative' },
    doubleTapHeart: {
        position: 'absolute',
        top: '50%',
        left: '50%',
        marginTop: -35,
        marginLeft: -35,
        width: 70,
        height: 70,
        justifyContent: 'center',
        alignItems: 'center',
    },
    mainImage: {
        width: '100%',
        aspectRatio: 16 / 11,
        backgroundColor: '#1a1a1a',
    },
    actionsRow: {
        paddingHorizontal: 16,
        paddingVertical: 12,
    },
    statItemRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 20,
    },
    statItem: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
    },
    statCount: {
        fontSize: 15,
        fontWeight: '500',
        color: '#fff',
    },
    heart: { fontSize: 24 },
    statIcon: { fontSize: 24 },
    body: { paddingHorizontal: 16, paddingTop: 0, paddingBottom: 16 },
    whatsLabel: {
        color: '#888',
        fontSize: 11,
        fontWeight: '600',
        marginBottom: 6,
        letterSpacing: 0.5,
    },
    descriptionFull: {
        color: '#e0e0e0',
        fontSize: 14,
        lineHeight: 20,
        marginBottom: 12,
    },
    stageRow: { marginTop: 0, marginBottom: 12 },
    stageText: { color: '#888', fontSize: 11, fontWeight: '600', letterSpacing: 0.5 },
    stageValue: { color: '#fff', fontWeight: '600', fontSize: 11 },
    pillsRow: { flexDirection: 'row', gap: 8, marginTop: 0, marginBottom: 12 },
    pill: {
        borderWidth: 1,
        borderColor: '#333',
        paddingHorizontal: 16,
        paddingVertical: 8,
        borderRadius: 6,
        backgroundColor: '#0f0f0f',
    },
    pillText: { color: '#fff', fontWeight: '500', fontSize: 12 },
    currentRound: { color: '#888', marginTop: 0, marginBottom: 8, fontSize: 12 },
    currentRoundValue: { color: '#fff', fontWeight: '600', fontSize: 14 },
    fundingBarWrap: { marginTop: 0 },
    fundingBarTrack: {
        height: 32,
        borderRadius: 6,
        backgroundColor: '#1a1a1a',
        overflow: 'hidden',
        borderWidth: 1,
        borderColor: '#333',
    },
    fundingFilled: { height: '100%', backgroundColor: '#666' },
    fundingLabelsRow: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 6 },
    filledLabel: { color: '#fff', fontSize: 12 },
    totalLabel: { color: '#fff', fontSize: 12 },
    menuButton: {
        padding: 4,
        marginLeft: 8,
    },
    cardBackground: {
        backgroundColor: '#070707',
        borderColor: '#0b0b0b',
    },
    rowCenter: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    whiteText: {
        color: '#fff',
    },
    flex1: {
        flex: 1,
    },
    verifiedSubtext: {
        color: '#878787',
        fontSize: 12,
        marginTop: 2,
    },
});
