import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    container: {}, // Remove flex: 1 to allow full scroll
    contentContainer: { flexGrow: 1, paddingBottom: 120 },
    topBar: { height: 56, paddingHorizontal: 12, alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' },
    iconButton: { width: 40, height: 40, alignItems: 'center', justifyContent: 'center', borderRadius: 8 },
    iconText: { fontSize: 25, fontWeight: '600' },
    topTitle: { fontWeight: '700', fontSize: 23 },
    loadingWrap: { padding: 28, alignItems: 'center' },
    profileHeader: { flexDirection: 'row', padding: 16, alignItems: 'center' },
    avatarWrap: { marginRight: 12 },
    avatarLarge: { width: 80, height: 80, borderRadius: 40, backgroundColor: '#333' },
    headerStats: { flexDirection: 'row', flex: 1, justifyContent: 'space-around' },
    statCol: { alignItems: 'center' },
    statNum: { fontWeight: '600', fontSize: 15 },
    statLabel: { fontWeight: '600', fontSize: 14.5 },
    setupPill: { marginHorizontal: 16, paddingVertical: 8, borderRadius: 999, borderWidth: 1, alignItems: 'center', marginBottom: 8 },
    setupPillText: { fontWeight: '600' },
    tabsRow: { flexDirection: 'row', marginTop: 8, position: 'relative' },
    tabItem: { flex: 1, paddingVertical: 12, alignItems: 'center' },
    tabText: { fontSize: 13 },
    tabTextActive: { fontSize: 13, fontWeight: '600' },
    tabUnderline: { height: 1, backgroundColor: '#fff', marginTop: 8, width: '70%', alignSelf: 'center' },
    tabIndicator: { height: 1.5, backgroundColor: '#fff', position: 'absolute', bottom: 0, width: '16.6667%', left: 0 },
    gridWrap: { padding: 12, flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between' },
    gridItem: { width: '31%', aspectRatio: 1, backgroundColor: '#222', borderRadius: 6, marginBottom: 12 },
    backdrop: { position: 'absolute', left: 0, top: 0, bottom: 0, right: 0, backgroundColor: 'rgba(0,0,0,0.4)' },
    leftDrawer: { position: 'absolute', right: 0, top: 0, bottom: 0, width: 300, padding: 16, borderLeftWidth: 1 },
    drawerTitle: { fontSize: 18, fontWeight: '700', marginBottom: 12 },
    fullPage: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, zIndex: 100 },
    settingsHeader: { height: 56, paddingHorizontal: 12, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: '#111' },
    headerBack: { width: 40, alignItems: 'flex-start', justifyContent: 'center' },
    settingsTitle: { fontSize: 18, fontWeight: '700' },
    settingsContent: { padding: 20, paddingBottom: 36 },
    sectionLabel: { fontSize: 13, fontWeight: '700', marginTop: 12, marginBottom: 8 },
    sectionCard: { borderWidth: 1, borderRadius: 12, overflow: 'hidden', backgroundColor: '#0b0b0b', marginBottom: 12 },
    settingRow: { padding: 14, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: '#111', flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
    settingLeft: { flex: 1, paddingRight: 8 },
    settingTitle: { fontSize: 15, fontWeight: '600' },
    settingSubtitle: { fontSize: 13.5, marginTop: 6 },
    chev: { fontSize: 18, paddingLeft: 8 },
    logoutBtn: { marginHorizontal: 16, backgroundColor: '#fff', borderRadius: 999, paddingVertical: 12, alignItems: 'center' },
    logoutText: { color: '#c41b1b', fontWeight: '700' },
    postCard: { padding: 12, margin: 12, borderRadius: 8, backgroundColor: '#101010' },
    pagerEmpty: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 24 },
    emptyTitle: { fontSize: 18, fontWeight: '700', marginBottom: 8 },
    emptyText: { fontSize: 14, textAlign: 'center', maxWidth: 420 },
    pagerWrap: { flex: 1, overflow: 'hidden' as any },
    pagerPage: { flex: 1, alignItems: 'center', justifyContent: 'center' },
    metaBlock: { paddingHorizontal: 16 },
    tagline: { fontSize: 14, fontWeight: '600', marginTop: 8 },
    description: { marginTop: 8, fontSize: 12, lineHeight: 16, maxWidth: 320 },
    badgesRow: { flexDirection: 'row', marginTop: 8, gap: 8 },
    badge: { paddingHorizontal: 8, paddingVertical: 4, borderRadius: 6, borderWidth: 1, marginRight: 8 },
    overviewCard: { padding: 12, margin: 12, borderRadius: 8, borderWidth: 1 },
    rowSpace: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 8 },
    infoLabel: { fontSize: 13 },
    infoValue: { fontSize: 13, fontWeight: '700' },
    milestones: { paddingHorizontal: 12, paddingTop: 8 },
    milestoneItem: { paddingVertical: 12, borderBottomWidth: 1, borderColor: '#eee' },
    milestoneTitle: { fontSize: 14, fontWeight: '700' },
    milestoneDate: { fontSize: 12, marginTop: 4 },
    milestoneDesc: { marginTop: 6 }
});
