module.exports = {
    User: require('./User'),
    Post: require('./Post'),
    Comment: require('./Comment'),
    Follow: require('./Follow'),
    Company: require('./Company'),
    StartupDetails: require('./StartupDetails'),
    InvestorDetails: require('./InvestorDetails'),
    VerificationDocument: require('./VerificationDocument'),
    VerificationStatus: require('./VerificationStatus'),
    Notification: require('./Notification'),
    SavedItem: require('./SavedItem'),
    Chat: require('./Chat'),
    Message: require('./Message'),
    Meeting: require('./Meeting'),
    Job: require('./Job'),
    Asset: require('./Asset'),
    Portfolio: require('./Portfolio'),
    AuditLog: require('./AuditLog'),
};
