import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#000',
    },
    scrollContent: {
        flexGrow: 1,
        justifyContent: 'center',
        paddingHorizontal: 20,
        paddingVertical: 40,
    },
    logoSection: {
        alignItems: 'center',
        marginBottom: 24,
    },
    formCard: {
        backgroundColor: '#0d0d0d',
        borderRadius: 10,
        borderWidth: 1,
        borderColor: '#262626',
        paddingHorizontal: 30,
        paddingVertical: 40,
    },
    input: {
        height: 50,
        backgroundColor: '#000',
        borderRadius: 10,
        paddingHorizontal: 14,
        marginBottom: 8,
        fontSize: 14,
        color: '#fff',
        borderWidth: 1,
        borderColor: '#363636',
    },
    dropdownButton: {
        height: 56,
        backgroundColor: '#000',
        borderRadius: 10,
        paddingHorizontal: 14,
        marginBottom: 8,
        borderWidth: 1,
        borderColor: '#363636',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    dropdownLabel: {
        color: '#8e8e8e',
        fontSize: 12,
        marginBottom: 2,
    },
    dropdownValue: {
        color: '#fff',
        fontSize: 14,
        fontWeight: '500',
    },
    dropdownArrow: {
        color: '#8e8e8e',
        fontSize: 12,
    },
    otpRow: {
        flexDirection: 'row',
        gap: 8,
        marginBottom: 12,
    },
    otpInput: {
        flex: 1,
        marginBottom: 0,
    },
    otpVerifyBtn: {
        backgroundColor: '#404040',
        paddingHorizontal: 20,
        borderRadius: 10,
        alignItems: 'center',
        justifyContent: 'center',
    },
    resendText: {
        color: '#0095f6',
        textAlign: 'center',
        fontSize: 13,
        marginTop: 8,
    },
    otpVerifyText: {
        color: '#fff',
        fontWeight: '600',
    },
    otpSection: {
        marginBottom: 0,
    },
    otpVerifySuccess: {
        backgroundColor: '#22c55e',
    },
    statusContainer: {
        paddingVertical: 8,
        marginBottom: 4,
    },
    statusMessage: {
        fontSize: 13,
        textAlign: 'center',
    },
    signupButton: {
        backgroundColor: '#404040',
        height: 50,
        borderRadius: 10,
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 15,
    },
    signupButtonDisabled: {
        backgroundColor: '#333333',
        opacity: 0.6,
    },
    signupButtonText: {
        color: '#fff',
        fontWeight: '600',
        fontSize: 14,
    },
    dividerRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginVertical: 20,
    },
    dividerLine: {
        flex: 1,
        height: 1,
        backgroundColor: '#363636',
    },
    dividerText: {
        marginHorizontal: 16,
        color: '#8e8e8e',
        fontSize: 12,
        fontWeight: '600',
    },
    googleButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 8,
    },
    googleText: {
        color: '#8e8e8e',
        fontWeight: '600',
        fontSize: 14,
        marginLeft: 8,
    },
    termsText: {
        color: '#8e8e8e',
        fontSize: 12,
        textAlign: 'center',
        marginTop: 16,
        lineHeight: 18,
    },
    signinCard: {
        borderWidth: 1,
        borderColor: '#262626',
        borderRadius: 10,
        backgroundColor: '#0d0d0d',
        paddingVertical: 20,
        marginTop: 16,
        alignItems: 'center',
    },
    signinText: {
        color: '#8e8e8e',
        fontSize: 14,
    },
    signinLink: {
        color: '#fff',
        fontWeight: '600',
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.8)',
        justifyContent: 'center',
        alignItems: 'center',
        padding: 20,
    },
    modalContent: {
        backgroundColor: '#0d0d0d',
        borderRadius: 10,
        borderWidth: 1,
        borderColor: '#262626',
        width: '100%',
        maxWidth: 340,
        padding: 24,
    },
    modalTitle: {
        color: '#fff',
        fontSize: 18,
        fontWeight: '700',
        textAlign: 'center',
        marginBottom: 20,
    },
    modalOption: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 14,
        paddingHorizontal: 14,
        borderRadius: 10,
        marginBottom: 8,
        backgroundColor: '#000',
        borderWidth: 1,
        borderColor: '#363636',
    },
    modalOptionActive: {
        backgroundColor: '#1a1a1a',
        borderColor: '#404040',
    },
    modalOptionContent: {
        flex: 1,
    },
    modalOptionLabel: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '600',
    },
    modalOptionLabelActive: {
        color: '#fff',
    },
    modalOptionDesc: {
        color: '#8e8e8e',
        fontSize: 13,
        marginTop: 2,
    },
    checkmark: {
        color: '#fff',
        fontSize: 18,
        fontWeight: '700',
    },
    modalCancel: {
        marginTop: 12,
        paddingVertical: 12,
        alignItems: 'center',
        backgroundColor: '#000',
        borderRadius: 10,
        borderWidth: 1,
        borderColor: '#363636',
    },
    modalCancelText: {
        color: '#8e8e8e',
        fontSize: 15,
        fontWeight: '600',
    },
    usernameContainer: {
        marginBottom: 8,
        position: 'relative',
        justifyContent: 'center',
    },
    usernameInput: {
        marginBottom: 0,
        paddingRight: 70,
    },
    checkButton: {
        position: 'absolute',
        right: 10,
        height: '100%',
        justifyContent: 'center',
        paddingHorizontal: 5,
    },
    checkText: {
        color: '#0095f6',
        fontSize: 13,
        fontWeight: '600',
    },
    statusIcon: {
        width: 24,
        height: 24,
        borderRadius: 12,
        borderWidth: 1.5,
        alignItems: 'center',
        justifyContent: 'center',
    },
    statusSuccess: {
        borderColor: '#4ade80',
    },
    statusError: {
        borderColor: '#ef4444',
    },
});
